### PR TITLE
checking for ambiguous csv formats

### PR DESCRIPTION
**Pull request by shaselton-usds**
## One line description of your change (less than 72 characters)
CSV format can be built in a way that the validator is unable to determine if it is a Wide or Tall format.

## Problem
When the validator encounters a CSV format that is without Tall specific column headers: payer_name and plan_name as well as lacking any payer/plan combinations that are found in the Wide format, the validator's default behavior was to try to validate the CSV against the Wide format ruleset. 

## Solution
The validator now checks for both types of formats before doing any additional validation.

## Result
The validator will now catch CSV files that do not have either a Tall or Wide format, throw an error, and inform the user to update their file to conform to either the Tall or Wide format.

## Test Plan

Unit tests added to check functionality.

### CODE REVIEW

**Review by mint-thompson — APPROVED** [review]
This looks like it perfectly handles the "not enough columns to tell" ambiguous case. Do we also want to add handling for the "too many columns" ambiguous case, where we have the `payer_name` and `plan_name` columns, and also at least one set of payer-plan columns?

**Review by eoverly — APPROVED** [review]
Looks good.  Thanks!

**Comment by shaselton-usds** [comment]
@mint-thompson updated to check for both wide and tall formats: https://github.com/CMSgov/hpt-validator/pull/40/commits/ee9aa8fb2c5efdf9147f94252ee71441f243f10b

**Comment by mint-thompson** [comment]
> @mint-thompson updated to check for both wide and tall formats: [ee9aa8f](https://github.com/CMSgov/hpt-validator/commit/ee9aa8fb2c5efdf9147f94252ee71441f243f10b)

Looks good, thank you!

**Pull request merged**
